# Generated by Django 2.2.1 on 2019-05-20 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_word', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('user_login', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo_title', models.CharField(max_length=100)),
                ('photo_file', models.FileField(upload_to='')),
                ('photo_like', models.IntegerField(default=0)),
                ('photo_tag', models.ManyToManyField(to='exhibit.Tag')),
                ('photo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibit.User')),
            ],
        ),
    ]
