# Generated by Django 2.2.1 on 2019-05-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0003_auto_20190520_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_user',
        ),
    ]
