# Generated by Django 2.2.1 on 2019-05-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0004_remove_photo_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created_date',
            field=models.DateTimeField(default='2019-05-20 18:07:15.821450+00:00'),
        ),
    ]
