# Generated by Django 2.2.1 on 2019-05-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0005_auto_20190520_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='created_date',
        ),
    ]
