# Generated by Django 2.2.1 on 2019-05-20 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0006_remove_photo_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='add_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
