# Generated by Django 2.2.1 on 2019-05-20 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0007_photo_add_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
