# Generated by Django 2.2.1 on 2019-05-23 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0012_auto_20190523_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='add_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime),
        ),
    ]
