# Generated by Django 2.2.1 on 2019-05-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0013_auto_20190523_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
