# Generated by Django 2.2.1 on 2019-05-25 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exhibit', '0016_auto_20190524_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('user_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
