# Generated by Django 2.2.1 on 2019-05-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0017_sendmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmessage',
            old_name='sent_on',
            new_name='senton',
        ),
        migrations.RenameField(
            model_name='sendmessage',
            old_name='user_form',
            new_name='userfrom',
        ),
        migrations.AddField(
            model_name='sendmessage',
            name='msgtitle',
            field=models.TextField(default='Wiadomość ze strony', max_length=100),
        ),
        migrations.AddField(
            model_name='sendmessage',
            name='useremail',
            field=models.EmailField(default='czesc@ithinkso.pl', max_length=254),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='msg',
            field=models.TextField(blank=True),
        ),
    ]
