# Generated by Django 2.2.1 on 2019-05-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0019_auto_20190525_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='msg',
            field=models.TextField(),
        ),
    ]
