# Generated by Django 2.2.1 on 2019-05-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0020_auto_20190525_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='useremail',
            field=models.EmailField(default='type@youremail.here', max_length=254),
        ),
    ]
