# Generated by Django 2.2.1 on 2019-05-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0023_newsletterusers_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterusers',
            name='news_from',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
