# Generated by Django 2.2.1 on 2019-05-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0025_inmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmail',
            name='title_txt',
            field=models.CharField(default='Nowa wiadomość InMail', max_length=100),
        ),
        migrations.AlterField(
            model_name='inmail',
            name='message_txt',
            field=models.TextField(),
        ),
    ]
